### PR TITLE
Remove upscaling

### PR DESCRIPTION
**Pull request by 8bitkick**
Revert to 640x512 as we don't seem to lose much quality and have PNG now for static images

### CODE REVIEW

**Comment by 8bitkick** [comment]
From Greg Kennedy: _Twitter accepts only "chroma quartered" YUV420P images, which can cause colors to bleed a bit on odd pixels.  I use it in @dot_scr to upscale 640x480 -> 1280x960 (nearest neighbor interp.) so the videos look better._

Need to test a few videos

**Comment by ojwb** [comment]
The code change in your patch is exactly what I tried locally.

It seems there may be reasons to upscale for videos and I agree we should test more before changing that.

Independent of that, I think it probably makes sense not to upscale in the PNG conversion, since the colour bleeding issues shouldn't affect those and the non-upscaled PNGs are a **lot** smaller (less than a tenth the size).

Incidentally, it's occurred to me we could probably fairly easily detect a result which is static apart from a blinking cursor and produce a PNG for those too - if there are exactly two unique frames we could compare them to see if the only difference is a short horizontal line.  I mention that here as it would allow producing PNG output in more cases.

**Comment by ojwb** [comment]
It occurs to me that the screen images we get are 640x512, so they're actually already effectively upscaled except in MODE0 (where the horizontal resolution really is 640) and MODE7 (where the interlace means the vertical resolution is effectively 500, with 12 unused lines).  So we could probably track if either of these two modes have been used and only upscale if they have.  (And for MODE7 any bleeding between the interlaced lines may not actually be bad thing.)

**Comment by 8bitkick** [comment]
We have to reject this change as although the speed up is nice the quality drops too much https://twitter.com/Kweepa/status/1275936672161705993?s=20

**Comment by ojwb** [comment]
I'm struggling a bit to conclude the second version is actually better, at least with what twitter serves me when I first look at each (it often seems to serve a better version if I return a while later - I'm unclear how it decides).

I'm OK to reject this idea though - I originally raised it as it wasn't clear that there was a reason for doing it, rather than it just being the end result of a series of incremental changes.

I do wonder if we should stop upscaling PNGs though - I can't see why that's helpful, and the file size is ~10 times smaller without.

**Comment by ojwb** [comment]
It seems I get a better version of the second one if I view directly at https://twitter.com/bbcmicrobot/status/1275938640154279939 instead of via the "tweet within a tweet reply".

**Pull request closed without merging**
