### PR TITLE
Fixed spacing when expanding tokenized keywords.

### PR DESCRIPTION
**Pull request by Kweepa**
Removed spaces after keywords that generally take parentheses.

### CODE REVIEW

**Comment by 8bitkick** [comment]
Sounds good 

CC @ojwb for visibility

**Comment by ojwb** [comment]
At a quick glance this looks OK, though adds spaces more generously than are needed.  I'm pretty sure only the pseudo-variables (`PAGE`, `COUNT`, etc) need a space after them to tokenise successfully.  In general the tokeniser is simply greedy, so e.g. `A ANDB` is fine (but the space before `AND` is needed to stop this being read as variable `AANDB`.

I don't know why the pseudo-variables are handled differently - if someone knows I'd be interested to hear.

But I think it'd be better to work out how to inject the tokenised program into beebjit.  Expanding tokens can making lines too long, changes offsets for code that peeks or pokes within the program, etc.  I'll try to take a look at doing that, but probably won't be until the weekend.

**Comment by Kweepa** [comment]
I actually removed spaces, since it was adding spaces after all tokens before. It's mostly for legibility and so that the syntax highlighter can identify the basic tokens, I think.

**Comment by ojwb** [comment]
Yes - I really meant "**still** adds spaces more generously than needed".

If this is for rendering a readable version of the program, that's fine - I assumed this was being done as a way to inject a pre-tokenised program into beebjit, but maybe I'm behind on the current situation there.

**Pull request merged**
