### PR TITLE
Refactor test code to use mock approach

### PR DESCRIPTION
**Pull request by ojwb**

### CODE REVIEW

**Comment by 8bitkick** [comment]
Nice! Everything is way cleaner with this refactor.

One thing although the CI tests claim to pass there are in fact unhandled ERRORs in the logs during the CHARACTERS test

```
2020-06-18T21:22:29.5653372Z [18/06/2020 21:22:29 ] [ERROR]  Cli0: (node:4133) UnhandledPromiseRejectionWarning: ReferenceError: audoInfo is not defined
2020-06-18T21:22:29.5653978Z     at Object.videoReply (/home/runner/work/BBCMicroBot/BBCMicroBot/test.js:93:27)
2020-06-18T21:22:29.5655913Z [18/06/2020 21:22:29 ] [ERROR]  Cli0: (node:4133) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2020-06-18T21:22:29.5656973Z [18/06/2020 21:22:29 ] [ERROR]  Cli0: (node:4133) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ojwb** [comment]
I'd missed that - will investigate.

**Comment by ojwb** [comment]
Fixed.

This also illustrates that we don't actually have a testcase for moving video with sound, so I added one.

**Comment by 8bitkick** [comment]
There is something a little strange happening because we are not `await`ing completion of the test funcs... the logs are out of order and for some reason GitHub CI terminated before pass OK for the final `AUDIOVISUAL` test. Did this happen when you did `npm test` or is it just GitHub?

**Comment by ojwb** [comment]
I had noticed the test results appearing a little interleaved and just put that down to node's obsession with asynchronicity, but it does also look like we don't wait for them all to complete.

I'll take a look, but it might take a while - there's no equivalent of `async` in BBC BASIC so it's beyond my comprehension.

**Comment by ojwb** [comment]
#12 seems to solve that, though maybe there's a better way.

**Pull request merged**
