### PR TITLE
Parse the HTML in the toot

### LINKED ISSUE #56: Strip mastodon tags and mentions properly
_@8bitkick mentioned this on mastodon - creating an issue for it so we can track progress better_

https://docs.joinmastodon.org/spec/microformats/ has the specs

### PR DESCRIPTION
**Pull request by ojwb**
This means that mentions and hashtags are now removed properly.

Fixes #56

### CODE REVIEW

**Comment by ojwb** [comment]
@8bitkick Probably you should check this one over rather than me just pushing it.

I wrote the testcase based on `mastodon.json`.

**Comment by 8bitkick** [comment]
Looks like an improvement to me, thanks! Couple of thoughts - 

Does this handle the case of `<br \>` as well as `<br></br>`?

I can see it ignoring `mentions` class but not `hashtag`? (https://docs.joinmastodon.org/spec/microformats/#hashtag)

**Comment by ojwb** [comment]
I didn't test `<br />` explicitly but to an HTML parser that's just really just an opening `<br>` tag so it ought to.

I only checked for `mention` because in `mastodon.json` that seemed to cover hashtags too, e.g.:

```
<a href="https://mastodon.me.uk/tags/bbcmicrobot" class="mention hashtag" rel="tag">#<span>bbcmicrobot</span></a>
```

**Comment by ojwb** [comment]
The spec does seem to suggest that `mention` is just for mentions though.  I'll investigate.  It's certainly easy to check for more classes if they're needed.

**Comment by 8bitkick** [comment]
In Twitter terminology a mention is an `@user` and a hashtag is a `#topic` I just assumed they're doing the same here, might be wrong

**Comment by ojwb** [comment]
The terminology seems the same and the spec does seem to suggest (as would be logical) that a mention gets class `mention` and a hashtag class `hashtag`, but in practice it seems that a hashtag gets both classes, at least with the current mastodon code.  You can see it here in the source: https://github.com/mastodon/mastodon/blob/main/app/lib/text_formatter.rb#L93

It probably makes sense to check for both though, so we're in line with the spec and more robust to changes (and differences in other implementations).  I can't really see a downside to doing so.  I'll push a change to do that.

**Comment by ojwb** [comment]
281f061388da115bf55d502be3ed5fdd75307c77 does that.

**Pull request merged**
